name: eslint-check
on: push
jobs:
    my-job:
        runs-on: ubuntu-latest
        strategy:
        # Node versions list
        matrix:
            node-version: [14.x]
        steps:
            - uses: actions/checkout@v2

            - name: Run linter
            run: make lint
